name: Deploy to Roblox

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Action to set up Python
        with:
          python-version: "3.9" # Specify the desired Python version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Compile Typescript
        run: npx rbxtsc

      # Run Rojo, deploy to Roblox
